### ISSUE TITLE
ctrl c does not work with bookmarks tab

### ISSUE THREAD

**Issue by stann-co** [thevenuz/xify#7]
pressing the copy link button, on a post will simply copy the current url and not the post

**Comment by thevenuz** [comment]
@jack27121 can you provide more details about the issue? And if possible, some screenshots and details of what you were expecting and how the extension is behaving?
Thanks!

**Comment by stann-co** [comment]
![image](https://github.com/user-attachments/assets/6b617dc2-a483-4356-be43-e23637ff98ad)
from my own bookmarks tab, pressing this button, gives me this link to paste 
https://vxtwitter.com/i/bookmarks
which is not usuable.
Tho i found out i can just click on the post to focus and then copy the link

**Comment by thevenuz** [comment]
@jack27121 Thanks for raising the issue. 

The PR #8 will fix this issue. The fix will be released soon in the version `2.1.3`. Once the fix is released the bhaviour will be: when a user goes to bookmarks page and uses "copy link" button on a post, the modified post link (vxtwitter/fxtwittter) will be copied clipboard. However, if Ctrl + C is used the extension will still copy the bookmarks page url to the clipboard.

**Comment by thevenuz** [comment]
The version `2.1.3` of the extension has been now released and this issue has been fixed.

Thanks!
